In [ ]:
import nltk

# Tokenization in NLP

In [ ]:
nltk.download('stopwords')
nltk.download("punkt")
nltk.download('wordnet')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
paragraph = """India, officially the Republic of India (Hindi: Bhārat Gaṇarājya),[26] is a country in South Asia. It is the seventh-largest country by area, 
            the second-most populous country, and the most populous democracy in the world. Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, 
            and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west;[f] China, Nepal, and Bhutan to the north; and Bangladesh and,
            Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; 
            its Andaman and Nicobar Islands share a maritime border with Thailand, Myanmar and Indonesia,
            Modern humans arrived on the Indian subcontinent from Africa no later than 55,000 years ago.[27][28][29] Their long occupation, 
            initially in varying forms of isolation as hunter-gatherers, has made the region highly diverse, second only to Africa in human 
            genetic diversity.[30] Settled life emerged on the subcontinent in the western margins of the Indus river basin 9,000 years ago, 
            evolving gradually into the Indus Valley Civilisation of the third millennium BCE.[31] By 1200 BCE, an archaic form of Sanskrit, 
            an Indo-European language, had diffused into India from the northwest,[32][33] unfolding as the language of the Rigveda, 
            and recording the dawning of Hinduism in India.[34] The Dravidian languages of India were supplanted in the northern and 
            western regions.[35] By 400 BCE, stratification and exclusion by caste had emerged within Hinduism,[36] and Buddhism and 
            Jainism had arisen, proclaiming social orders unlinked to heredity.[37] Early political consolidations gave rise to the 
            loose-knit Maurya and Gupta Empires based in the Ganges Basin.[38] Their collective era was suffused with wide-ranging 
            creativity,[39] but also marked by the declining status of women,[40] and the incorporation of untouchability into an organised system of belief.
            [g][41] In South India, the Middle kingdoms exported Dravidian-languages scripts and religious cultures to the kingdoms of Southeast Asia.[42]"""

In [ ]:
# converting paragraph into sentences

sentences = nltk.sent_tokenize(paragraph)
print(len(sentences))
sentences

13


['India, officially the Republic of India (Hindi: Bhārat Gaṇarājya),[26] is a country in South Asia.',
 'It is the seventh-largest country by area, \n            the second-most populous country, and the most populous democracy in the world.',
 'Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, \n            and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west;[f] China, Nepal, and Bhutan to the north; and Bangladesh and,\n            Myanmar to the east.',
 'In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; \n            its Andaman and Nicobar Islands share a maritime border with Thailand, Myanmar and Indonesia,\n            Modern humans arrived on the Indian subcontinent from Africa no later than 55,000 years ago.',
 '[27][28][29] Their long occupation, \n            initially in varying forms of isolation as hunter-gatherers, has made the region highly diverse, second only to Africa in human \

In [ ]:
# converting paragraph into words

words = nltk.word_tokenize(paragraph)
print(len(words))
words

# Stemming and lemmatization 

In [ ]:
# stemming ( keep the common for words, used in sentiment analysis models)
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [ ]:
stemmer = PorterStemmer()

In [ ]:
for i in range(len(sentences)):
  tmp_word = nltk.word_tokenize(sentences[i])

  tmp_word = [stemmer.stem(word) for word in tmp_word if word not in set(stopwords.words('english'))]
  sentences[i] = " ".join(tmp_word)

In [ ]:
sentences

['india , offici republ india ( hindi : bhārat gaṇarājya ) , [ 26 ] countri south asia .',
 'It seventh-largest countri area , second-most popul countri , popul democraci world .',
 'bound indian ocean south , arabian sea southwest , bay bengal southeast , share land border pakistan west ; [ f ] china , nepal , bhutan north ; bangladesh , myanmar east .',
 'In indian ocean , india vicin sri lanka maldiv ; andaman nicobar island share maritim border thailand , myanmar indonesia , modern human arriv indian subcontin africa later 55,000 year ago .',
 '[ 27 ] [ 28 ] [ 29 ] their long occup , initi vari form isol hunter-gather , made region highli divers , second africa human genet divers .',
 '[ 30 ] settl life emerg subcontin western margin indu river basin 9,000 year ago , evolv gradual indu valley civilis third millennium bce .',
 '[ 31 ] By 1200 bce , archaic form sanskrit , indo-european languag , diffus india northwest , [ 32 ] [ 33 ] unfold languag rigveda , record dawn hinduism ind

In [ ]:
# Lemetizer ( keep the meaning of word, used in chatbot)
from nltk.stem import WordNetLemmatizer

In [ ]:
lemma = WordNetLemmatizer()

In [ ]:
for i in range(len(sentences)):
  tmp_word = nltk.word_tokenize(sentences[i])
  tmp_word = [lemma.lemmatize(word) for word in tmp_word if word not in set(stopwords.words('english'))]
  sentences[i] = " ".join(tmp_word)

In [ ]:
sentences

['India , officially Republic India ( Hindi : Bhārat Gaṇarājya ) , [ 26 ] country South Asia .',
 'It seventh-largest country area , second-most populous country , populous democracy world .',
 'Bounded Indian Ocean south , Arabian Sea southwest , Bay Bengal southeast , share land border Pakistan west ; [ f ] China , Nepal , Bhutan north ; Bangladesh , Myanmar east .',
 'In Indian Ocean , India vicinity Sri Lanka Maldives ; Andaman Nicobar Islands share maritime border Thailand , Myanmar Indonesia , Modern human arrived Indian subcontinent Africa later 55,000 year ago .',
 '[ 27 ] [ 28 ] [ 29 ] Their long occupation , initially varying form isolation hunter-gatherer , made region highly diverse , second Africa human genetic diversity .',
 '[ 30 ] Settled life emerged subcontinent western margin Indus river basin 9,000 year ago , evolving gradually Indus Valley Civilisation third millennium BCE .',
 '[ 31 ] By 1200 BCE , archaic form Sanskrit , Indo-European language , diffused India no

# Bag of words with lemmitazation

In [ ]:
from nltk.internals import read_int
import re

corpus = []
for i in range(len(sentences)):
  # taking only alphabets
  review = re.sub('[^a-zA-Z]',' ', sentences[i])
  review = review.lower()
  review = review.split()
  review = [lemma.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
  review = " ".join(review)
  corpus.append(review)

NameError: ignored

In [ ]:
corpus

In [ ]:
# Creating bag of words

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=1500)
x = cv.fit_transform(corpus).toarray()
print(len(x))
x

13


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# TF IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer()
x = cv.fit_transform(corpus).toarray()
print(len(x))
x

# Word2Vec

In [ ]:
from gensim.models import Word2Vec

In [ ]:

text = re.sub(r"\[[0-9]*\]", " ", paragraph)
# removing special character
text = re.sub(r"\s+", " ", text)
# converting all in lower
text = text.lower()
text = re.sub(r"\d", " ", text)
text = re.sub(r"\s+", " ", text)
text

'india, officially the republic of india (hindi: bhārat gaṇarājya), is a country in south asia. it is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world. bounded by the indian ocean on the south, the arabian sea on the southwest, and the bay of bengal on the southeast, it shares land borders with pakistan to the west;[f] china, nepal, and bhutan to the north; and bangladesh and, myanmar to the east. in the indian ocean, india is in the vicinity of sri lanka and the maldives; its andaman and nicobar islands share a maritime border with thailand, myanmar and indonesia, modern humans arrived on the indian subcontinent from africa no later than , years ago. their long occupation, initially in varying forms of isolation as hunter-gatherers, has made the region highly diverse, second only to africa in human genetic diversity. settled life emerged on the subcontinent in the western margins of the indus river basin , years ago, e

In [ ]:
sentences = nltk.sent_tokenize(text)
sentences = [nltk.word_tokenize(sentence) for sentence in sentences ]

In [ ]:
for i in range(len(sentences)):
  sentences[i] = [word for word in sentences[i] if word not in set(stopwords.words('english'))]

In [ ]:
sentences

In [ ]:
model = Word2Vec(sentences, min_count=1)

In [ ]:
words = model.wv.vocab
words

In [ ]:
vector = model.wv['india']
len(vector)

100

In [ ]:
similar = model.wv.most_similar('asia')
similar

[('country', 0.24626584351062775),
 ('populous', 0.2228507101535797),
 ('g', 0.22104939818382263),
 ('consolidations', 0.21067361533641815),
 ('southwest', 0.1958770900964737),
 ('dravidian-languages', 0.18834611773490906),
 ('within', 0.18729442358016968),
 (':', 0.18541505932807922),
 ('dravidian', 0.16651472449302673),
 ('hindi', 0.16215012967586517)]

# Spam Detection

In [ ]:
import pandas as pd

In [ ]:
message = pd.read_csv('SMSSpamCollection', sep='\t', names=["labels", "message"])

In [ ]:
message

labels                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
ps = PorterStemmer()
corpus = []
for i in range(len(message)):
  review = re.sub("[^a-zA-z]", " ", message.iloc[i][1])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
  review = " ".join(review)
  corpus.append(review)

In [ ]:
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()

y = pd.get_dummies(message.iloc[:,0])

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y = y.iloc[:,1]
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: uint8

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

In [ ]:
# train model using Naive bayer claassifier

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB().fit(x_train, y_train)

In [ ]:
pre = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, pre)

In [ ]:
cm

array([[956,  10],
       [  7, 142]])

In [ ]:
accuracy_score(y_test, pre)

0.9847533632286996

# Stock market sentiment analysis

In [ ]:
import pandas as pd
data = pd.read_csv("Data.csv", encoding = "ISO-8859-1")
data

Date  Label                                               Top1  \
0     2000-01-03      0  A 'hindrance to operations': extracts from the...   
1     2000-01-04      0                                          Scorecard   
2     2000-01-05      0                  Coventry caught on counter by Flo   
3     2000-01-06      1                      Pilgrim knows how to progress   
4     2000-01-07      1                               Hitches and Horlocks   
...          ...    ...                                                ...   
4096  2016-06-27      0  Barclays and RBS shares suspended from trading...   
4097  2016-06-28      1  2,500 Scientists To Australia: If You Want To ...   
4098  2016-06-29      1                   Explosion At Airport In Istanbul   
4099  2016-06-30      1  Jamaica proposes marijuana dispensers for tour...   
4100  2016-07-01      1  A 117-year-old woman in Mexico City finally re...   

                                                   Top2  \
0                                             Scorecard   
1                                   The best lake scene   
2                    United's rivals on the road to Rio   
3                                   Thatcher facing ban   
4                        Beckham off but United survive   
...                                                 ...   
4096  Pope says Church should ask forgiveness from g...   
4097  The personal details of 112,000 French police ...   
4098  Yemeni former president: Terrorism is the offs...   
4099  Stephen Hawking says pollution and 'stupidity'...   
4100   IMF chief backs Athens as permanent Olympic host   

                                                   Top3  \
0                       Hughes' instant hit buoys Blues   
1                         Leader: German sleaze inquiry   
2         Thatcher issues defence before trial by video   
3               McIlroy calls for Irish fighting spirit   
4                               Breast cancer screening   
...                                                 ...   
4096  Poland 'shocked' by xenophobic abuse of Poles ...   
4097  S&amp;P cuts United Kingdom sovereign credit r...   
4098  UK must accept freedom of movement to access E...   
4099  Boris Johnson says he will not run for Tory pa...   
4100  The president of France says if Brexit won, so...   

                                                   Top4  \
0              Jack gets his skates on at ice-cold Alex   
1                                         Cheerio, boyo   
2         Police help Smith lay down the law at Everton   
3                       Leicester bin stadium blueprint   
4                                           Alan Parker   
...                                                 ...   
4096  There will be no second referendum, cabinet ag...   
4097                Huge helium deposit found in Africa   
4098  Devastated: scientists too late to captive bre...   
4099  Six gay men in Ivory Coast were abused and for...   
4100  British Man Who Must Give Police 24 Hours' Not...   

                                                   Top5  \
0                Chaos as Maracana builds up for United   
1                              The main recommendations   
2           Tale of Trautmann bears two more retellings   
3                        United braced for Mexican wave   
4               Guardian readers: are you all whingers?   
...                                                 ...   
4096      Scotland welcome to join EU, Merkel ally says   
4097  CEO of the South African state broadcaster qui...   
4098  British Labor Party leader Jeremy Corbyn loses...   
4099  Switzerland denies citizenship to Muslim immig...   
4100  100+ Nobel laureates urge Greenpeace to stop o...   

                                                   Top6  \
0     Depleted Leicester prevail as Elliott spoils E...   
1                                Has Cubie killed fees?   
2                                   England on the rack   
3  

In [ ]:
train = data[data['Date'] < '20150101']
test = data[data['Date'] >= '20150101']

In [ ]:
td = train.iloc[:,2:27]
td.replace("[^a-zA-Z]", " ", regex=True, inplace = True)

list1 = [i for i in range(25)]
new_index = [str(i) for i in list1]
td.columns = new_index
td.head(2)

0                    1  \
0  A  hindrance to operations   extracts from the...            Scorecard   
1                                          Scorecard  The best lake scene   

                                 2                                         3  \
0  Hughes  instant hit buoys Blues  Jack gets his skates on at ice cold Alex   
1    Leader  German sleaze inquiry                             Cheerio  boyo   

                                        4  \
0  Chaos as Maracana builds up for United   
1                The main recommendations   

                                                   5  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees    

                                  6                                  7  \
0  Hungry Spurs sense rich pickings  Gunners so wide of an easy target   
1            Has Cubie killed fees              Has Cubie killed fees    

                                                   8  \
0      Derby raise a glass to Strupar s debut double   
1  Hopkins  furious  at Foster s lack of Hannibal...   

                                          9  ...  \
0  Southgate strikes  Leeds pay the penalty  ...   
1                    Has Cubie killed fees   ...   

                                         15  \
0  Flintoff injury piles on woe for England   
1                      On the critical list   

                                                  16  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   

                                    17  \
0  Kohl s successor drawn into scandal   
1                          Dear doctor   

                                                  18  \
0               The difference between men and women   
1  Irish court halts IRA man s extradition to Nor...   

                                                  19  \
0                Sara Denver  nurse turned solicitor   
1  Burundi peace initiative fades after rebels re...   

                                               20  \
0  Diana s landmine crusade put Tories in a panic   
1            PE points the way forward to the ECB   

                                                  21                22  \
0  Yeltsin s resignation caught opposition flat f...  Russian roulette   
1  Campaigners keep up pressure on Nazi war crime...    Jane Ratcliffe   

                                                  23  \
0                                           Sold out   
1  Yet more things you wouldn t know without the ...   

                             24  
0            Recovering a title  
1  Millennium bug fails to bite  

[2 rows x 25 columns]

In [ ]:
for ind in new_index:
  td[ind] = td[ind].str.lower()
td.head(1)  

0          1  \
0  a  hindrance to operations   extracts from the...  scorecard   

                                 2                                         3  \
0  hughes  instant hit buoys blues  jack gets his skates on at ice cold alex   

                                        4  \
0  chaos as maracana builds up for united   

                                                   5  \
0  depleted leicester prevail as elliott spoils e...   

                                  6                                  7  \
0  hungry spurs sense rich pickings  gunners so wide of an easy target   

                                               8  \
0  derby raise a glass to strupar s debut double   

                                          9  ...  \
0  southgate strikes  leeds pay the penalty  ...   

                                         15  \
0  flintoff injury piles on woe for england   

                                                  16  \
0  hunters threaten jospin with new battle of the...   

                                    17                                    18  \
0  kohl s successor drawn into scandal  the difference between men and women   

                                    19  \
0  sara denver  nurse turned solicitor   

                                               20  \
0  diana s landmine crusade put tories in a panic   

                                                  21                22  \
0  yeltsin s resignation caught opposition flat f...  russian roulette   

         23                  24  
0  sold out  recovering a title  

[1 rows x 25 columns]

In [ ]:
td.tail(1)

0  \
3974  microsoft corp said on wednesday it will begin...   

                                                      1  \
3974  greek orthodox church  homosexuals are god s c...   

                                                      2  \
3974  vladmir putin officially dissolves roscosmos  ...   

                                                      3  \
3974  donald trump could be refused entry to the uk ...   

                                                      4  \
3974  saudi arabia says its ready to meet any additi...   

                                                      5  \
3974  new year fireworks and festivities have been c...   

                                                      6  \
3974  new species of human may have shared our caves...   

                                                      7  \
3974  egypt becomes second nation to shut down faceb...   

                                                      8  \
3974  polish government takes control of public medi...   

                                                      9  ...  \
3974  from jan    uk to stop financial aid to india ...  ...   

                                                     15  \
3974  ramadi residents fleeing isis   they wanted to...   

                                                     16  \
3974  israeli gov t approves nis    billion plan to ...   

                                                     17  \
3974  russia denies  absurd  claims that air strikes...   

                                          18  \
3974  web attack knocks bbc websites offline   

                                                    19  \
3974  iran says any u s  sanctions on missiles illegal   

                                                     20  \
3974  maternity benefits  indian government plans to...   

                                                     21  \
3974   rat on a plane  forces air india flight to tu...   

                                                     22  \
3974  philippines to join china backed aiib infrastr...   

                                                     23  \
3974  espn invites five fifa presidential candidates...   

                                                     24  
3974  hamas to keep palestinians from ringing in new...  

[1 rows x 25 columns]

In [ ]:
headline = []
for row in range(len(td)):    
  headline.append(" ".join(str(x) for x in td.iloc[row,0:25]))

In [ ]:
headline

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier


In [ ]:
cv = CountVectorizer(ngram_range=(2,2))
train_d = cv.fit_transform(headline)

In [ ]:
model = RandomForestClassifier(n_estimators=200, criterion='entropy')
model.fit(train_d, train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [ ]:
test_headline = []
for row in range(len(test)):    
  test_headline.append(" ".join(str(x) for x in test.iloc[row,2:27]))

test_d = cv.transform(test_headline)  

In [ ]:
len(test_headline)

126

In [ ]:
pred = model.predict(test_d)

In [ ]:
len(pred)

126

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(test['Label'], pred)

In [ ]:
cm

array([[10, 46],
       [13, 57]])

 # Fake news classifier

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/train.csv", encoding='latin-1')
df.head(1)

id                                              title         author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s...  Darrell Lucus   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s...      1

In [ ]:
x = df.drop('label', axis=1)
x.head(1)

id                                              title         author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s...  Darrell Lucus   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s...

In [ ]:
y = df['label']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer


In [ ]:
df = df.dropna()

In [ ]:
message = df.copy()
message.reset_index(inplace=True)

In [ ]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re

ps = PorterStemmer()

corpus = []

for i in range(len(message)):
  review = re.sub("[^a-zA-Z]"," ", message['title'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
  review = " ".join(review)
  corpus.append(review)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, ngram_range=(2,2))
X = cv.fit_transform(corpus).toarray()

In [ ]:
y=message['label']

In [ ]:
from sklearn import model_selection
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y, random_state=42, test_size=0.2)

In [ ]:
cv.get_feature_names()

In [ ]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (2, 2),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [ ]:
count_df = pd.DataFrame(x_train)
count_df

In [ ]:
from sklearn import naive_bayes
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

model.fit(x_train, y_train)
pred = model.predict(x_test)

In [ ]:
from nltk import metrics
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)
cm

array([[1907,  175],
       [ 677,  898]])

# passive aggressive classifier

In [ ]:
from sklearn.linear_model import PassiveAggressiveClassifier
lin_model = PassiveAggressiveClassifier(max_iter=50)

In [ ]:
lin_model.fit(x_train, y_train)
pred = lin_model.predict(x_test)
cm = confusion_matrix(y_test, pred)
cm

array([[1643,  439],
       [  56, 1519]])

# multinomial classifier with hyperparameter

In [ ]:
classifier = MultinomialNB(alpha=0.1)

In [ ]:
import sklearn
import numpy as np
from sklearn.metrics import accuracy_score

prev_score = 0
for alpha in np.arange(0,1,0.1):
  
  sub_model = MultinomialNB(alpha=alpha)
  sub_model.fit(x_train, y_train)
  y_pred = sub_model.predict(x_test)
  score = accuracy_score(y_test, y_pred)
  print(score)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:557: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  % _ALPHA_MIN


0.7571780147662018
0.7686628383921247
0.7697566311184031
0.7700300792999727
0.7700300792999727
0.7681159420289855
0.7667487011211376
0.7670221493027072
0.7670221493027072
0.7667487011211376


# Word embedding with keras

In [ ]:
from keras.preprocessing.text import one_hot

In [ ]:
sentence = ["the glass of milk",
            "the glass of juice",
            "i am a good boy",
            "understand the meaning",
            "your videos are good"]

In [ ]:
voc_size = 10000

In [ ]:
onehot_sent = [one_hot(words, voc_size) for words in sentence]
onehot_sent

[[324, 5833, 8413, 4948],
 [324, 5833, 8413, 6840],
 [9625, 7563, 1193, 4809, 1045],
 [6768, 324, 7122],
 [5378, 2176, 1927, 4809]]

# Word embedding

In [ ]:
from keras.layers import Embedding, LSTM, Dense, Dropout
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import numpy as np

In [ ]:
from gensim.matutils import pad
sent_l = 8
embedded = pad_sequences(onehot_sent, padding='pre', maxlen=sent_l)
embedded

array([[   0,    0,    0,    0,  324, 5833, 8413, 4948],
       [   0,    0,    0,    0,  324, 5833, 8413, 6840],
       [   0,    0,    0, 9625, 7563, 1193, 4809, 1045],
       [   0,    0,    0,    0,    0, 6768,  324, 7122],
       [   0,    0,    0,    0, 5378, 2176, 1927, 4809]], dtype=int32)

In [ ]:
dim = 15

In [ ]:
model = Sequential()
model.add(Embedding(voc_size, 15, input_length=sent_l))
model.compile('adam', 'mse')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 15)             150000    
                                                                 
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.predict(embedded)

In [ ]:
model.predict(embedded[0])

array([[-0.03015925, -0.03700181,  0.0446083 ,  0.04006027, -0.03383664,
         0.02871597, -0.03615773, -0.04672622,  0.03441199, -0.02341638,
         0.03590367, -0.03995843, -0.00548173, -0.01363111, -0.03005326],
       [-0.03015925, -0.03700181,  0.0446083 ,  0.04006027, -0.03383664,
         0.02871597, -0.03615773, -0.04672622,  0.03441199, -0.02341638,
         0.03590367, -0.03995843, -0.00548173, -0.01363111, -0.03005326],
       [-0.03015925, -0.03700181,  0.0446083 ,  0.04006027, -0.03383664,
         0.02871597, -0.03615773, -0.04672622,  0.03441199, -0.02341638,
         0.03590367, -0.03995843, -0.00548173, -0.01363111, -0.03005326],
       [-0.03015925, -0.03700181,  0.0446083 ,  0.04006027, -0.03383664,
         0.02871597, -0.03615773, -0.04672622,  0.03441199, -0.02341638,
         0.03590367, -0.03995843, -0.00548173, -0.01363111, -0.03005326],
       [ 0.01255033, -0.01388117,  0.00227948, -0.01808159, -0.03711464,
        -0.03131342,  0.04491737, -0.00208696, 

# 2nd model

In [ ]:
# adding a LSTM layer
embedding_vector_feature = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_feature, input_length=sent_l))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 8, 40)             400000    
                                                                 
 dropout (Dropout)           (None, 8, 40)             0         
                                                                 
 lstm_4 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 456,501
Trainable params: 456,501
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# scale down the values
from sklearn.preprocessing import MinMaxScaler 

# scale up ( reverse )
scaler.inverse_transform